# Redis数据库索引（默认为0）database=0
# Redis服务器地址
#spring:
#  redis:
#    database: 0
#    host: redis # localhost
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 3000 # 连接超时时间（毫秒）, 2.x不能为0